name: 'Deque Accessibility Issue Labeler'
description: 'Labels issues automatically for accessibility based on their body'
author: 'Deque Systems, Inc.'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
    default: ${{ github.token }}
  include-title:
    description: 'Include the title in addition to the body in the regex target'
    required: false
    default: "0"
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'activity'
  color: 'blue'
