name: Accessibility Violation Form
description: Document an accessibility violation to be fixed
title: "[A11Y]: "
labels: ["a11y", "PROD: a11y-poc"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to inform us about this accessiblity issue!
  - type: textarea
    id: short-desc
    attributes:
      label: What happened?
      description: Please tell us briefly what the issue was
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: What is the impact of the violation?
      options:
        - BLOCKER (Default)
        - CRITICAL
        - SERIOUS
        - MODERATE
        - MINOR
    validations:
      required: true
  - type: dropdown
    id: successcriteria
    attributes:
      label: Success Criteria
      description: What WCAG Success Criteria best matches this violation?
      multiple: true
      options:
        - 1.1.1 Non-text Content [x]
        - 1.2.1 Audio-only and Video-only (Prerecorded) [x]
        - 1.2.2 Captions (Prerecorded) [x]
        - 1.2.3 Audio Description or Media Alternative (Prerecorded) [x]
        - 1.2.4 Captions (Live) [x]
        - 1.2.5 Audio Description (Prerecorded) [x]
        - 1.2.6 Sign Language (Prerecorded) [x]
        - 1.2.7 Extended Audio Description (Prerecorded) [x]
        - 1.2.8 Media Alternative (Prerecorded) [x]
        - 1.2.9 Audio-only (Live) [x]
        - 1.3.1 Info and Relationships [x]
        - 1.3.2 Meaningful Sequence [x]
        - 1.3.3 Sensory Characteristics [x]
        - 1.3.4 Orientation [x]
        - 1.3.5 Identify Input Purpose [x]
        - 1.3.6 Identify Purpose [x]
        - 1.4.1 Use of Color [x]
        - 1.4.2 Audio Control [x]
        - 1.4.3 Contrast (Minimum) [x]
        - 1.4.4 Resize text [x]
        - 1.4.5 Images of Text [x]
        - 1.4.6 Contrast (Enhanced) [x]
        - 1.4.7 Low or No Background Audio [x]
        - 1.4.8 Visual Presentation [x]
        - 1.4.9 Images of Text (No Exception) [x]
        - 1.4.10 Reflow [x]
        - 1.4.11 Non-text Contrast [x]
        - 1.4.12 Text Spacing [x]
        - 1.4.13 Content on Hover or Focus [x]
        - 2.1.1 Keyboard [x]
        - 2.1.2 No Keyboard Trap [x]
        - 2.1.3 Keyboard (No Exception) [x]
        - 2.1.4 Character Key Shortcuts [x]
        - 2.2.1 Timing Adjustable [x]
        - 2.2.2 Pause, Stop, Hide [x]
        - 2.2.3 No Timing [x]
        - 2.2.4 Interruptions [x]
        - 2.2.5 Re-authenticating [x]
        - 2.2.6 Timeouts [x]
        - 2.3.1 Three Flashes or Below Threshold [x]
        - 2.3.2 Three Flashes [x]
        - 2.3.3 Animation from Interactions [x]
        - 2.4.1 Bypass Blocks [x]
        - 2.4.2 Page Titled [x]
        - 2.4.3 Focus Order [x]
        - 2.4.4 Link Purpose (In Context) [x]
        - 2.4.5 Multiple Ways [x]
        - 2.4.6 Headings and Labels [x]
        - 2.4.7 Focus Visible [x]
        - 2.4.8 Location [x]
        - 2.4.9 Link Purpose (Link Only) [x]
        - 2.4.10 Section Headings [x]
        - 2.5.1 Pointer Gestures [x]
        - 2.5.2 Pointer Cancellation [x]
        - 2.5.3 Label in Name [x]
        - 2.5.4 Motion Actuation [x]
        - 2.5.5 Target Size [x]
        - 2.5.6 Concurrent Input Mechanisms [x]
        - 3.1.1 Language of Page [x]
        - 3.1.2 Language of Parts [x]
        - 3.1.3 Unusual Words [x]
        - 3.1.4 Abbreviations [x]
        - 3.1.5 Reading Level [x]
        - 3.1.6 Pronunciation [x]
        - 3.2.1 On Focus [x]
        - 3.2.2 On Input [x]
        - 3.2.3 Consistent Navigation [x]
        - 3.2.4 Consistent Identification [x]
        - 3.2.5 Change on Request [x]
        - 3.3.1 Error Identification [x]
        - 3.3.2 Labels or Instructions [x]
        - 3.3.3 Error Suggestion [x]
        - 3.3.4 Error Prevention (Legal, Financial, Data) [x]
        - 3.3.5 Help [x]
        - 3.3.6 Error Prevention (All) [x]
        - 4.1.1 Parsing [x]
        - 4.1.2 Name, Role, Value [x]
        - 4.1.3 Status Messages [x]
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How did you find this issue?
      description: Provide clear steps for how to reproduce this issue.
      placeholder: Tell us how you found this issue!
    validations:
      required: true
  - type: textarea
    id: actual-outcome
    attributes:
      label: What was the unexpected behaviour that causes the issue?
      description: Please describe what behaviors are causing the accessbility issue
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: actual-behiavor
    attributes:
      label: What should have happened instead?
      description: Please provide us with the desired outcome of this issue
      placeholder: Give us help in how to fix this issue!
    validations:
      required: true
  - type: input
    id: auditorid
    attributes:
      label: Auditor Link
      description: If manual issue, provive the link to Auditor Test Run Issue
      placeholder: https://axeauditor.dequecloud.com/
    validations:
      required: false
  - type: textarea
    id: element
    attributes:
      label: Element Source Code
      description: Please copy and paste relevant element source. This will be automatically formatted into code, so no need for backticks.
      render: HTML
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Links to Screenshots
      description: Please provide links to screnshots
    validations:
      required: false
  - type: checkboxes
    id: extras
    attributes:
      label: 'Additional Context'
      description: 'Mark any and all checkboxes that apply'
      options:
        - label: Found during VPAT
        - label: Found using NVDA
        - label: Found using Chrome Screen Reader
        - label: Found using custom configurations
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true